# general
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}

# containers
FPM_IMAGE=php:8-fpm-alpine
FPM_ENTRYPOINT=${FPM_ENTRYPOINT}

TOOL_IMAGE=php:8-fpm-alpine
TOOL_ENTRYPOINT=${TOOL_ENTRYPOINT}

NGINX_IMAGE=nginx:1.19.3-alpine
DOCUMENT_ROOT=/var/www/public

# network
NETWORK=${NETWORK}
NETWORK_PROXY_PORT=${NETWORK_PROXY_PORT}
NGINX_VIRTUAL_HOST=${PROJECT_NAME}.127.0.0.1.nip.io

# volumes
PROJECT_DIR=${PROJECT_DIR}
NGINX_CONF=${NGINX_CONF}

